<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Imad-PC" name="com.jukinmedia.qatest.vaccumcleaner.TestCase2" tests="3" failures="1" timestamp="22 Feb 2016 18:23:24 GMT" time="1.355" errors="0">
  <testcase name="verifyLogo" time="0.446" classname="com.jukinmedia.qatest.vaccumcleaner.TestCase2">
    <failure type="java.lang.AssertionError" message="expected [44] but found [15]">
      <![CDATA[java.lang.AssertionError: expected [44] but found [15]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at com.jukinmedia.qatest.vaccumcleaner.utilities.BasePage.assertValue(BasePage.java:85)
	at com.jukinmedia.qatest.vaccumcleaner.pages.SectionOneToFive.verifyLogoPosition(SectionOneToFive.java:181)
	at com.jukinmedia.qatest.vaccumcleaner.TestCase2.verifyLogo(TestCase2.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- verifyLogo -->
  <testcase name="verifyComName" time="0.373" classname="com.jukinmedia.qatest.vaccumcleaner.TestCase2"/>
  <testcase name="verifyComMoto" time="0.536" classname="com.jukinmedia.qatest.vaccumcleaner.TestCase2"/>
</testsuite> <!-- com.jukinmedia.qatest.vaccumcleaner.TestCase2 -->
